### ISSUE TITLE
Keep "workdir"

### ISSUE THREAD

**Issue by ZARk-be** [tachtler/dovecot-backup#11]
How about an option to avoid deleting then decompressing the tar file, but just keeping the workdir ?
Sure it takes more space, but makes backup much faster and uses less active resources.

**Comment by tachtler** [comment]
Hi ZARk-be,

what did you mean exactly?

You would like to have the files from `dsync` command at `$DIR_BACKUP/$DOMAINPART` still available and no tar.gz?

```
# CUSTOM - Backup-Files.
DIR_BACKUP='/srv/backup'
...
DOMAINPART=${users#*@} 
```
For example: `/srv/backup/tachtler.net`

This would mean, however, that you do not have a status on the backup day x, but more and more individual e-mail files are added and also deleted or moved files are still available and the directory then inexorably grows.

Thank you
Klaus.

**Comment by ZARk-be** [comment]
Hello

What i understand from your script.
0/ if a .Tar.gz file exists it decompresses it
1/ it uses dsync to sync the files
2/ it makes a new .tar.gz
3/ it deletes the directory.

What i would like, is an option, to keep the "temporary" synced directory, instead of deleting it everytime.
As to avoid decompressing and deleting so many files, as it takes a long time on my backup hdd.

**Comment by tachtler** [comment]
Hi ZARk-be,

0/ if a .Tar.gz file exists it decompresses it - **No, that's false**, the mailbox files will be generated by using the command `dsync`.

The `dsync` determines the individual e-mail files by user and writes them to 
`LOCATION="$DIR_BACKUP/$DOMAINPART/$LOCALPART/$MAILDIR_NAME"`

The `dsync` command was **not** called via `sync` is was called via `backup` command extension.

See also: https://wiki.dovecot.org/Tools/Doveadm/Sync

Thank you
Klaus.

**Comment by ZARk-be** [comment]
Yes off course "doveadm backup" . Otherwise you change the source files.

But then you backup ALL files EVERYTIME ? 
doveadm backup would just update only changes if you keep the destination files instead of deleting them (and remove the -f option).


Why this choice?

**Comment by tachtler** [comment]
Hi ZARk-be,

the script has the **task to create a daily backup** of all e-mails per user, so that for **N days a backup copy per day can be kept**.

See the file system example below:
```
-rw------- 1 vmail vmail 80035325 Feb 13 04:03 klaus@tachtler.net-dovecot_backup_20190213_040001.tar.gz
-rw------- 1 vmail vmail 80362784 Feb 14 04:03 klaus@tachtler.net-dovecot_backup_20190214_040001.tar.gz
-rw------- 1 vmail vmail 80857070 Feb 15 04:04 klaus@tachtler.net-dovecot_backup_20190215_040001.tar.gz
-rw------- 1 vmail vmail 80515623 Feb 16 04:03 klaus@tachtler.net-dovecot_backup_20190216_040001.tar.gz
-rw------- 1 vmail vmail 80592212 Feb 17 04:04 klaus@tachtler.net-dovecot_backup_20190217_040001.tar.gz
-rw------- 1 vmail vmail 80481210 Feb 18 04:03 klaus@tachtler.net-dovecot_backup_20190218_040001.tar.gz
-rw------- 1 vmail vmail 80724049 Feb 19 04:04 klaus@tachtler.net-dovecot_backup_20190219_040001.tar.gz
-rw------- 1 vmail vmail 80803602 Feb 20 04:04 klaus@tachtler.net-dovecot_backup_20190220_040001.tar.gz
```
If I have understood you correctly, you would like to have a running copy of the emails without unpacking a tar.gz file. If this is the case, you might want to set up a **second Dovecot and possibly implement a** time-delayed **replication of the two Dovecot instances**. 

The option `-f` is optimal for the actual purpose of the script, since I aim for full synchronization with this script.

> Full synchronization (-f parameter) scans through all the messages in all the mailboxes.  This guarantees that everything will be synchronized, but it's unnecessarily slow for incremental synchronization.

Thank you
Klaus.

**Comment by tachtler** [comment]
Hi,

I will close this issue, because no response to it in the last week.

Klaus.
