### ISSUE TITLE
Maybe need to implement a "tmp" dir for dsync usage and separate it from final .tar.gz destination ? (permission problems over NFS / etc mounts)

### ISSUE THREAD

**Issue by worgenrage** [tachtler/dovecot-backup#12]
Hey there! Just wanted to try / use your script to backup dovecot maildirs / user emails.

https://pastebin.com/CB3y9Lxu

Just check this, as you can see i want to backup to a remote NFS mount, which causing permission problems. As i read the script, dsync try to do the "extract" directly to the backup target directory (/mnt/NFS/...) then create .tar.gz backup file from there.

Is there any way / chance to specify a "tmp" directory for dsync, which is different from BACKUP_DIR target ? Because it should solve the permission problems.

dsync want to use / run / put extration via the actual email user (USER.NAME in pastebin example) that will fail, because that user has 0 permission for the backup target directory. And this is good.

Any way to implement a "TMP_DSYNC_EXTRACT" directory for dsync operations, and keep BACKUP_DIR for backup target where the .tar.gz file will lands.

Sorry for my english, not my native.

Thanks!

Regards
Christian Hamar
Hungary

**Comment by tachtler** [comment]
Hi Christian,

why did you specify for: 
`DIR_BACKUP='/mnt/NFS/MAIL/emails/'`

You can specify **`DIR_BACKUP='/tmp'`** and then you can make a **copy job transferring it to you target destination?** 

If the script will offer the possibility to specify a temporary file, how would you transfer the data to the NFS? **Should the dovecot-backup script do that too?**

And what would be different then, than to set the corresponding permissions equal, because for a copy job, the corresponding permissions must also be available?

I'd like to restrict the dovecot-backup script to its actual purpose, **but let us discuss**, if you want?

Thank you
Klaus.

**Comment by worgenrage** [comment]
Hello Klaus! Thanks for the answer!

Well, i just wanted to do all things in one place with one script. Your dovecot-backup script :)

My permission problems occured when dsync did the exporting. via user@mail* username. (nevermind what i specifiy) because dsync and chmod in the scripts wants to create dsync extract via user@mail perms on ex.: an NFS mount, which does not know anything about that user or neither any system user where the backup script running.

If i set a "local" path for dovecot-backup, then of course i don't have any permission problems when dsync extract running, because its local, it know users / groups. But when i try to backup directly to NFS (or anything else, that does not know anything about my local users) then it will fail.

Of course i can do dovecot-backup to ex.: /_BACKUP/ (just said something) locally. Then move the .tar.gz to the NFS mount via another script.

But that is another script to run no? :) 

My suggestion was, maybe make a (well not call it tmppath) 
DSYNC_EXTRACT_PATH=""   and then a DIR_BACKUP="" and make a choice for users, to user DSYNC_EXTRACT_PATH set to local server (so dsync extract will be running fine with perms/users) and make a DIR_BACKUP to the final destination of .tar.gz backup files.

Because as i see dsync extract its only a temporary thing here, because when it finished, a targz will be generated from there, then dsync extract files will be gone. Or no ?

And well, if i copy the tar.gz to the final destination, then whats the point in BACKUPFILES_DELETE ?

Because if i move my targz to another path, then i just lost the BACKUPFILES_DELETE "function".

No offense its just a simple suggestion.

Best regards!
Christian Hamar
Hungary

**Comment by tachtler** [comment]
Hi Christian,

can I sent you a new version for testing?

Thank you
Klaus.

**Comment by worgenrage** [comment]
Hi Klaus,

sure, just drop a link in mail christian.hamar_AT_gmail_DOT_com .

Probably i can test it today evening.

Regards
Christian

**Comment by tachtler** [comment]
Hi Christian,

I will sent you an e-Mail in the next view minutes, NO additional settings in CUSTOM area are required - I will create e temporary local directory with mktemp!

Thank you for testing

**Comment by tachtler** [comment]
Hi Christian,

e-Mail with Verison 1.11 was sent to you for testing purpose.

Thank you for your help!
Klaus.

**Comment by tachtler** [comment]
Hi Christian,

have you been able to test the last version I sent you?

Thank you for your help!
Klaus.

**Comment by tachtler** [comment]
Version: 1.11
Description: GitHub Issue #12

Change of the temporary storage medium from DIR_BACKUP to TMP_FOLDER for temporary storage of extracted emails from the mailboxes was introduced. This allows the use of a temporary storage of the extracted emails from the mailboxes on a faster storage medium, or also on a local storage medium, which avoids rights problems if DIR_BACKUP is e.g. an NFS mounted storage.

Thanks to Krisztián Hamar.
