### ISSUE TITLE
Change VAR_EMAILDATE timezone format to offset in hours

### ISSUE THREAD

**Issue by velzebop** [tachtler/dovecot-backup#16]
Not all email UIs are ok with the three letter timezone notation. Proposal is to change the notation to offset in hours  

Current format is: Sun, 17 May 2020 10:41:48 (BST)
Proposed format is Sun, 17 May 2020 10:41:48 (+0100)

Line 176 would then be updated to 
VAR_EMAILDATE=`$DATE_COMMAND '+%a, %d %b %Y %H:%M:%S (%z)'`

**Comment by tachtler** [comment]
Hi velzebop,

changed in Version 1.13. (I will upload them in a view minutes!)

Thank you for your contribution to dovecot_backup.sh

Thank you!
Klaus.

**Comment by velzebop** [comment]
No worries
