### ISSUE TITLE
crontab error

### ISSUE THREAD

**Issue by danilodorgam** [tachtler/dovecot-backup#17]
I currently have this error
dovecot_backup.sh: line 231: -f: command not found
But I only have it when I roll via crontab
running via crontab
`0 4 * * *   bash /opt/dovecot-backup/dovecot_backup.sh`
running manually

`bash /opt/dovecot-backup/dovecot_backup.sh`

**Comment by tachtler** [comment]
Hi Danilo,

which OS/Distribution are you using?

Can you change your crontab entry like this:
```
# Backup dovecot mailboxes.
00 04 * * * root /opt/dovecot_backup/dovecot_backup.sh
```
p.s. The ```sendmail``` binary seems to be the problem.

Greetings
Klaus.

**Comment by tachtler** [comment]
Hi Danilo,

see the issue #14, maybe this could be the solution for your problem too?

Greetings
Klaus.

**Comment by tachtler** [comment]
Sorry for closing!

**Comment by danilodorgam** [comment]
Thanks, the solution worked for my case
