### ISSUE TITLE
Add "-" (dash) to valid characters in regex mail validity check

### ISSUE THREAD

**Issue by ghost** [tachtler/dovecot-backup#18]
Mail addresses with a dash in the user or domainname get rejected by the script.

Adding dash to valid characters will fix this problem.

**Comment by tachtler** [comment]
Hi Henrik,

I will release version 1.14 as soon as possible, as bugfix for your reported problem.

Thank you for contributing dovecot-backup.sh
Klaus.

**Comment by tachtler** [comment]
Hi Henrik,

is that at your opinion o.k. to use that for the regex check:
```^[a-zA-Z0-9-]*@[a-zA-Z0-9-]*\.[a-zA-Z0-9]*$```
because you will prefer:
```^[a-zA-Z0-9.-]*@[a-zA-Z0-9.-]*\.[a-zA-Z0-9]*$```

Thank you!
Klaus.

**Comment by ghost** [comment]
Hi @tachtler,

I myself use mail addresses with fullstops in the username, so I think it would be wise to include these in the regex. Additionally I removed the digits in the TLD part, because there's no known TLD including digits to me. So this is my proposal: `^[a-zA-Z0-9.-]*@[a-zA-Z0-9.-]*\.[a-zA-Z]*$`

**Comment by tachtler** [comment]
Hi Henrik,

change the version 1.14 to your regex!

Thank you!
Klaus.
