### ISSUE TITLE
Mailbox doesn't allow inferior mailboxes

### ISSUE THREAD

**Issue by nikall** [tachtler/dovecot-backup#2]
Hi,

Just used your script to backup my imap/pop3 server mailboxes and I got the error above from dsync trying to backup a specific user mailbox. This happens only with this specific user because there is a folder created (by the user) using their mail client (they have created a Archives folder below Inbox). 

` Error: Can't create mailbox Archives/2018: Mailbox doesn't allow inferior mailboxes`

In my dovecot file I have enabled the LAYOUT=fs option which supposedly should solve this issue but without any improvement. 

Could you please help me ?

Thanks in advance.

**Comment by tachtler** [comment]
Hi,

please see:  
https://help.bittitan.com/hc/en-us/articles/115008253328-Mailbox-doesn-t-allow-inferior-mailboxes

It seems to be a problem/BUG of Dovecot.

Maybe you can solve this, by changing the folder structure or move the  
email from a main folder to a defined subfolder?

Klaus.

> Hi,
>
> Just used your script to backup my imap/pop3 server mailboxes and I  
> got the error above from dsync trying to backup a specific user  
> mailbox. This happens only with this specific user because there is  
> a folder created (by the user) using their mail client (they have  
> created a Archives folder below Inbox).
>
> ` Error: Can't create mailbox Archives/2018: Mailbox doesn't allow  
> inferior mailboxes`
>
>
> In my dovecot file I have enabled the LAYOUT=fs option which  
> supposedly should solve this issue but without any improvement.
>
> Could you please help me ?
>
> Thanks in advance.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tachtler/dovecot-backup/issues/2


----- Ende der Nachricht von nikall <notifications@github.com> -----




-- 

------------------------------------------------
e-Mail  : klaus@tachtler.net
Homepage: https://www.tachtler.net
DokuWiki: https://dokuwiki.tachtler.net
------------------------------------------------

**Comment by tachtler** [comment]
Hi,

maybe this can help:  
https://superuser.com/questions/813362/sub-folders-in-dovecot

Klaus.

> Hi,
>
> Just used your script to backup my imap/pop3 server mailboxes and I  
> got the error above from dsync trying to backup a specific user  
> mailbox. This happens only with this specific user because there is  
> a folder created (by the user) using their mail client (they have  
> created a Archives folder below Inbox).
>
> ` Error: Can't create mailbox Archives/2018: Mailbox doesn't allow  
> inferior mailboxes`
>
>
> In my dovecot file I have enabled the LAYOUT=fs option which  
> supposedly should solve this issue but without any improvement.
>
> Could you please help me ?
>
> Thanks in advance.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tachtler/dovecot-backup/issues/2


----- Ende der Nachricht von nikall <notifications@github.com> -----




-- 

------------------------------------------------
e-Mail  : klaus@tachtler.net
Homepage: https://www.tachtler.net
DokuWiki: https://dokuwiki.tachtler.net
------------------------------------------------

**Comment by tachtler** [comment]
Hi,

could you solve the problem?

Klaus.

**Comment by tachtler** [comment]
Hi,

I will close this issue, because no response to it in the last three weeks.

Klaus.
