### ISSUE TITLE
TMP_FOLDER

### ISSUE THREAD

**Issue by LarsBel** [tachtler/dovecot-backup#21]
Hallo,

bei mir funktioniert das Skript nicht, wenn der TMP_FOLDER nicht dem MAILDIR_USER gehört.

Ich hab also folgendes gemacht:
`if [ ! -d "$TMP_FOLDER" ]; then`
`        logline "Check if TMP_FOLDER exists " false`
`	$MKDIR_COMMAND -p $TMP_FOLDER`
        **$CHOWN_COMMAND -R $MAILDIR_USER:$MAILDIR_GROUP $TMP_FOLDER**

OS: Ubuntu 20.04 -> umask 027 und ich benutze dsync

**Comment by tachtler** [comment]
Hallo LarsBel,

danke für die Unterstützung, ich habe Deine Änderungen in Version 1.15 übernommen.

Grüße
Klaus.

---

Hello LarsBel,

Set the required ownership on TMP_FOLDER before running the script was done in version 1.15.

Thank you!
Klaus.
