### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by Alphix** [tachtler/dovecot-backup#24]
The LICENSE file in the root dir says GPL-3.0:

https://github.com/tachtler/dovecot-backup/blob/41415f4e4020b0e42e6b4cc16da54842eaf8c3aa/LICENSE#L1-L2

While the actual script says GPL-2.0 or later:

https://github.com/tachtler/dovecot-backup/blob/41415f4e4020b0e42e6b4cc16da54842eaf8c3aa/dovecot_backup.sh#L17-L22

**Comment by tachtler** [comment]
Hi David,

thank you for the note of the license mismatch. I will correct that, as soon as possible.

Thank you,
Klaus.

**Comment by tachtler** [comment]
New Version 1.18 was uploaded.
