### ISSUE TITLE
Backing up tmp and dovecot-uidlist.lock?

### ISSUE THREAD

**Issue by ozgurkazancci** [tachtler/dovecot-backup#28]
Hello.

When it comes to backing up a dovecot server, there are suggestions under "**Issues**" on a replyby 'JojOatXGME' here: https://serverfault.com/a/758551 which is talking about the tmp directory and the file dovecot-uidlist.lock

Would you consider those statements for the dovecot-backup script?

Best.

**Comment by tachtler** [comment]
Hi Özgür,

the script uses the `dsync` or `doveadm` command to create a backup while the dovecot server is running. As far as I know, it is not possible to exclude an internal technical directory such as `tmp`, `cur`, `new` using the command. There would be the option:
```
       -x mailbox_mask
              Exclude the specified mailbox name/mask.  The mask may contain “?” and “*” wildcards. 
              This parameter can be used multiple times which refers to a mailbox.
```

I haven't had any problems with this yet.

Regards
Klaus.

**Comment by tachtler** [comment]
Hi Özgür,

is it o.k., when I close that issue?

Regards
Klaus.

**Comment by ozgurkazancci** [comment]
Sure, thanks a lot for your explanation.
