### ISSUE TITLE
Error by Run Script

### ISSUE THREAD

**Issue by achmet9948** [tachtler/dovecot-backup#3]
Hello, 

if i start the script, the following error messages is comming: 
"dovecot_backup.sh: 110: dovecot_backup.sh: Syntax error: "(" unexpected"

Can you help me?

**Comment by tachtler** [comment]
Hi,

line number 110 is:

function log() {

Did you download the script correctly?
Wich OS you are using?


Klaus.

----- Nachricht von achmet9948 <notifications@github.com> ---------
      Datum: Tue, 06 Mar 2018 21:57:14 +0000 (UTC)
        Von: achmet9948 <notifications@github.com>
Antwort an: tachtler/dovecot-backup  
<reply@reply.github.com>
    Betreff: [tachtler/dovecot-backup] Error by Run Script (#3)
         An: tachtler/dovecot-backup <dovecot-backup@noreply.github.com>
         Cc: Subscribed <subscribed@noreply.github.com>


> Hello,
>
> if i start the script, the following error messages is comming:
> "dovecot_backup.sh: 110: dovecot_backup.sh: Syntax error: "(" unexpected"
>
> Can you help me?
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tachtler/dovecot-backup/issues/3


----- Ende der Nachricht von achmet9948 <notifications@github.com> -----




-- 

------------------------------------------------
e-Mail  : klaus@tachtler.net
Homepage: https://www.tachtler.net
DokuWiki: https://dokuwiki.tachtler.net
------------------------------------------------

**Comment by tachtler** [comment]
Hi,

I will close this issue, because no response to it in the last three weeks.

Klaus.
