### ISSUE TITLE
Feature Request: Add summary of failed mailboxes | add error-handling

### ISSUE THREAD

**Issue by HenrikWMG** [tachtler/dovecot-backup#4]
Hello, Ich use this really nice script but i have 2 requests:

First Request: Can you add some error-handling? For example in row 298

`$DSYNC_COMMAND -o plugin/quota= -f -u $users backup $MAILDIR_TYPE:$LOCATION`
is no error handling. Due to an bug in dovecot in version 2.3.0 and higher, the dysnc command failed in our environment for shared mailboxes because of an problem with ACLs. The script gives no feedback no matter it failed or succeded. Can you change this? Especially for:

` $DSYNC_COMMAND -o plugin/quota= -f -u $users backup $MAILDIR_TYPE:$LOCATION` (row 298)
`$TAR_COMMAND -cvzf $users-$FILE_BACKUP $USERPART --atime-preserve --preserve-permissions` (row 303)

Second Request: Add an summary for failed mailboxes so the user get an output like:
```
INFO: +-----------------------------------------------------------------+
INFO: | End backup dovecot_backup ..................................... |
INFO: | Successfully saved mailboxes: 15
INFO: | Errors in mailboxes:
INFO: |    - mmuster@domain.tld
INFO: |    - mmuster2@domain.tld
INFO: |    - mmuster3@domain.tld
......
INFO: +-----------------------------------------------------------------+

```
We save around 50 mailboxes with this script. If you save so many or more mailboxes this summary 
helps to determine which mailboxes have issues or not.

sincerely yours

**Comment by tachtler** [comment]
Hi HenrikWMG,

I'll see what I can do for you.

I will try to implement your wishes (because I don't have so much time today) in the next few days in a few steps.

Klaus.

**Comment by tachtler** [comment]
Hi HenrikWMG,

I've made some changes to a new version 1.05 - So can you try that version?

Thank you!
Klaus.

**Comment by HenrikWMG** [comment]
Hi Tachtler,

your changes look pretty good and thank you already that you responded this fast.
I can test your changes tomorrow and will give you a specific feedback.

Sincerely yours

HenrikWMG

**Comment by tachtler** [comment]
Hi HenrikWMG,

tell me if everything is fine for you, so I will close this issue.

Thank you
Klaus.

**Comment by HenrikWMG** [comment]
So far i didn't find any problems. I made a quick test with a testing environment. This night this script will run in our production environment. If i didnt write in the next 2 days you can close this issue. 
Both requests got fulfilled 100%

Thank you very much for your afford and quick responses. 

Sincerely yours,

HenrikWMG

**Comment by HenrikWMG** [comment]
In the past days everything works good. With your script we were even able to find several bugged mailboxes that we will fix in the future. Thank you very much again. I close this issue for you.

Sincerely yours,

HenrikWMG

**Comment by tachtler** [comment]
Hi HenrikWMG,

thank you for your participation and testing!

Klaus.
