### ISSUE TITLE
Script funktioniert bei MDbox nicht

### ISSUE THREAD

**Issue by SvenSFS** [tachtler/dovecot-backup#6]
Hallo,
bei der Konfiguration mit Dovecot mit IPConfig und mdbox läuft das Script nicht
richtig.

Für das Backup kann man 
`doveadm backup -f -n inbox -u $user maildir:/srv/backup:LAYOUT=fs`
benutzen.

Eingebaut in dein Script hat das Super Funktioniert.
DANKE!!!!! für deine Arbeit.

Das Tachtler Wiki gibt immer wieder Denkanstöße.

Gruss
Sven

**Comment by tachtler** [comment]
Hallo Sven,

danke für Deinen Hinweis zum Thema Dovecot Multi-dbox.

Da mein Skript ja dsync verwendet und Du eine Lösung mit doveadm backup gefunden hast, würde ich das in die README Datei aufnehmen, wenn das für Dich o.k. wäre?

Danke auch für das Lob zu meinem DokuWiki.

Grüße
Klaus.

**Comment by tachtler** [comment]
Hallo Sven,

ich habe die README Datei angepasst. Passt das so für Dich?

Danke und Grüße
Klaus.

**Comment by SvenSFS** [comment]
Also eigentlich egal, solange der User die Möglichkeit hat zum Ziel zu kommen
ist das Okay. Die Frage ist wo der Unterschied zwischen dsync und doveadm backup ist?
Ich hab im Netz dazu nicht sinnvolles gefunden.

Gruß
Sven

**Comment by tachtler** [comment]
Hallo Sven,

eine gute Frage. Ich habe dazu folgendes gefunden:

- [https://wiki2.dovecot.org/Tools/Doveadm/Sync](https://wiki2.dovecot.org/Tools/Doveadm/Sync)

Ich denke `dsync` ist das Synonym für `dovecot sync`. Evtl. könnte das Skript generell auch den Befehl `dovecot backup` verwenden. Das werde ich mal überprüfen.

Grüße
Klaus.

**Comment by tachtler** [comment]
Hallo Sven,

ich denke dsync ist ein synonym für doveadm backup, evtl. wird es dsync in zukünftigen Versionen von dovecot ggf. nicht mehr geben, mal sehen.

Aktuell würde ich aber gerne mein Skript so belassen wie es ist, aber in der README Deinen Hinweis aufgenommen lassen.

Danke für die Deine Unterstützung
Grüße
Klaus.
