### ISSUE TITLE
crontab does not work

### ISSUE THREAD

**Issue by hatted** [tachtler/dovecot-backup#7]
It works fine if i run the script from command manually, but it does not work when i run it in crontab.  I checked it runs from the first line but not finish at the last line.  Is there any permission I need to set?

**Comment by hatted** [comment]
Sorry, I found out how to fix it.   It cannot find out the sendmail command.  I need to use the bash shell to run your script in crontab.  Now problem fixed.  Thanks.

**Comment by tachtler** [comment]
Hi hatted,

I use the command (in bash shell) 
```
PROG_SENDMAIL=`command -v sendmail` 
```
to detect where the `sendmail` program was to find at the OS.

Maybe you could use the full path to `sendmail` or you can use other programs like `mutt`, or did you find another solution?

p.s.  This was your solution for `/etc/crontab` ...?
```
#!/bin/bash
```

Greetings
Klaus.

**Comment by hatted** [comment]
I was using the other shell in crontab which cannot run the sbin folder.
0 2 * * 0 /bin/sh /root/script/dovecot_backup.sh > /dev/null 2>&1
Then i changed to bash and it works now.
0 2 * * 0 bash -lc /root/script/dovecot_backup.sh > /dev/null 2>&1

Thanks for your great script.

**Comment by tachtler** [comment]
Hi hatted,

thank you for posting you solution.

Greetings
Klaus.
