### ISSUE TITLE
Feature request: only backup selected mailboxes

### ISSUE THREAD

**Issue by graueRitter** [tachtler/dovecot-backup#9]
Good morning, 

I like your script, and have also learnt some generic bash techniques I can use in unrelated scripts. However, I want to be able to select which user mailboxes I backup.

So I have expanded your script by making the following modifications:
- Moved personal options to a separate backup configuration file that is read by the script (this configuration file is now a command line option for backup_dovecot.sh).
- Added backup list path and filename variable to the backup configuration file that points to a list of mailboxes to back for that backup configuration.
- Created a file listing mailboxes to backup that is read by the configuration file as per added variable to backup configuration file.
- Created a backup user function that backup only specified user's mailbox that is called via iterating a list generated either from your original all dovecot mailboxes command or a list of users to backup if it exists. Defaults to backing up all mailboxes.

This does add to the number of files but allows the following new features:
- One can define and schedule multiple backups each with different options for the case where not all backups should have the same configuration.
- One can backup individual mailboxes or groups of mailboxes, each with their own backup configuration options.
- One can easily have different backups (e.g. weekly and monthly backups saving to different locations) that backup the same set of mailboxes. Or different mailboxes.

Would you be interested in this code and how should I get it to you? 

I'm still very new to GitHub, but it seems the standard method of contributing is for me to fork your repository, make changes, and issue you with a pull request that you can then (if happy with changes) merge with your code. Is this what you  would like me to do?

Thanks,

graue

**Comment by tachtler** [comment]
Good morning and a happy new year graue Ritter,

yes, I'm very interested in your code. So please fork the `dovecot-backup.sh` and add a pull request, or send me your code by email as zip or tar-ball, do it like you want.

I'm always interested, how people expand the code, and if it makes `dovecot-backup.sh` better, everybody can benefit from it!

Thank you, and I'm looking forward to your changes.
Klaus.

**Comment by graueRitter** [comment]
Hi Klaus,

thank you for the new year wishes, so far the year has started well.

Happy new year to you as well, I hope you have a good upcoming year.

I've forked your code, added changes, and generated the pull request. It took a little longer than I expected as I wanted to improve the robustness and logging of the users/mailboxes to be backed up file.

Have a good week,

graue

**Comment by tachtler** [comment]
Hi graue Ritter,

sorry for the long time with no answer from me.

Thank you for your contribution on dovecot-backup script. 

I think about the pro and con of your changes, but I'm not sure, if it is the right way to change the code into that direction.

Maybe, we can discuss this here also with other people?

Thank you!
Klaus.

**Comment by kbridger** [comment]
I can't speak to the implementation, but in terms of direction for the script this is something I definitely would like to use.  Right now I run the script via cron and every report I get back is a failure, because not all mailboxes were backed up.  And nor should they be.  I don't want users like spamd, nobody, etc to be backed up.  And any failed mailbox results in the report indicating an overall failure.

Being able to identify which users to backup would be a definite improvement for my workflow.  Having a config option to identify which users to backup makes sense

**Comment by graueRitter** [comment]
Hi,

Klaus: no need to apologise for the delay, I understand people have higher priorities and commitments.
kbridger: good point about not wanting specific mailboxes backed up and it being useful to be able to specify users/mailboxes to back up.

My current main programming familiarity is with compiled languages (C++/C) so I instinctively followed the normal paradigm to allow different run time configurations which is specifying run time configurations either as a command line parameter and/or in a separate configuration file. Unlike compiled programmes, with shell scripts the user of the script can easily edit to configure so this may have been excessive for this script.

With regards to implementation, assuming this is a direction Klaus wishes to go with this script I could:
- Move the configuration back into the main script at the top (current location for configuration settings).
- Add a 'list' (only just started learning bash scripting so will need to learn how to implement this in bash) variable 'USER_LIST' (for example) to the configuration to contain the users/mailboxes to backup.
- In the main script where the list of users/mailboxes to be backed up is generated check if $USER_LIST is populated: if it is, use that list, else get list of users/mailbox from `doveadm user "*"`.

This would keep everything in the one script with all the attendant advantages of a single script. Different backup configurations can be created by 'copy script and edit' method.

Personally I'd prefer the separate configuration and backup list files as I believe that offers greater flexibility (and worth the extra complexity), but it is, of course, up to Klaus.

**Comment by tachtler** [comment]
Hi Everybody,

sorry for the late update to version 1.08.

Version     : 1.08
Description : GitHub Issue #9
               Add ability to only backup specific mailboxes, by using the
               variable FILE_USERLIST with the file path and file name as
               content. The file must contain one e-mail address per line.
               Add the calculation of the script runtime.
               Thanks to graue Ritter.

Thank you all,
Klaus.

**Comment by kbridger** [comment]
Great to see this merged - thank you!

I've pulled the latest code this morning and am testing the userlist capability.  I see that the script verifies that each user listed in the userlist file is in the form of an email address.  However doveadm on my system does not find those users when formatted as an email address.

The main script works because the username "kirk" resolves in doveadm.  But for me, the username "kirk@domain.com" does not resolve to an actual user in the system, and the script fails to find any users to backup.

Is the email format of the user listing required?  Do I need to change my install so that doveadm will recognize email addresses instead of just user names?

**Comment by tachtler** [comment]
Hi kbridger,

I mistakenly assumed that the **username** is always an email address, that was my mistake.

In Version 1.09 there will be a switch `FILE_USERNAME_VALIDATE_EMAIL='N'` to enable or disable the e-mail address validation check - especially made for you,  but it was my mistake!

I will upload the new version in the next few minutes.

Thank you for helping me making dovecot_backup.sh better!
Klaus.

**Comment by tachtler** [comment]
Hi Everybody,

Update to Version 1.09
Add a switch to enable or disable e-mail address check, when FILE_USERLIST was set and used.

Thanks to kbridger.
Klaus.

**Comment by kbridger** [comment]
Tested with latest version and it works perfectly - thank you!

**Comment by tachtler** [comment]
Hi kbridger,

thank you for your feedback!

Maybe you can test the next version too, which will be uploaded in the next few hours? Thank you in advance!

Klaus.
